---
sidebar: sidebar 
permalink: ontap-security-hardening/autonomous-ransomware-protection.html 
keywords: tr-4569, ontap hardening guide, security, ARP, fpolicy, UBA, ransomware, machine learning, volume workloads, entropy 
summary: La capacidad de aprendizaje automático integrada de ONTAP detecta el ransomware basado en las cargas de trabajo del volumen y la entropía. 
---
= Protección autónoma contra ransomware de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Para complementar el análisis del comportamiento de los usuarios para la Seguridad de las cargas de trabajo de almacenamiento, la protección autónoma frente al ransomware de ONTAP analiza las cargas de trabajo de volumen y la entropía para detectar el ransomware y realiza una instantánea y notifica al administrador cuando se sospecha de un ataque.

Además de la detección y prevención de ransomware mediante el análisis del comportamiento del usuario (UBA) externo de FPolicy con NetApp Data Infrastructure Insights Storage Workload Security y el ecosistema de socios de NetApp FPolicy, ONTAP 9.10.1 presenta protección autónoma contra ransomware.  La protección autónoma contra ransomware de ONTAP utiliza una capacidad de aprendizaje automático (ML) incorporada que analiza la actividad de la carga de trabajo del volumen más la entropía de los datos para detectar ransomware automáticamente.  Monitorea la actividad que es diferente a la de UBA para poder detectar ataques que UBA no detecta.

Para obtener información más detallada sobre esta capacidad, consulte link:../ransomware-solutions/ransomware-overview.html["Soluciones de NetApp para ransomware"] o link:https://docs.netapp.com/us-en/ontap/anti-ransomware/use-cases-restrictions-concept.html["Documentación autónoma de protección contra ransomware de ONTAP"^].
