---
sidebar: sidebar 
permalink: ontap-security-hardening/security-hardening-overview.html 
keywords: tr-4569, ontap hardening guide, security, threats, threat landscape, hardening guide, introduction 
summary: Utilice esta guía para ONTAP para ayudar a su organización a cumplir los objetivos de seguridad prescritos sobre la confidencialidad, la integridad y la disponibilidad del sistema de información. 
---
= Información general sobre el refuerzo de la seguridad de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP ofrece un conjunto de controles que permiten fortalecer el sistema operativo de almacenamiento de ONTAP, el software para la gestión de datos líder del sector. Utilice las directrices y los ajustes de configuración de ONTAP para ayudar a su organización a cumplir los objetivos de seguridad prescritos de confidencialidad, integridad y disponibilidad del sistema de información.

La evolución del panorama actual de amenazas presenta a una organización retos únicos para proteger sus activos más valiosos: Los datos y la información. Las amenazas y vulnerabilidades avanzadas y dinámicas a las que nos enfrentamos son cada vez más sofisticadas. Junto con un aumento en la eficacia de las técnicas de ofuscación y reconocimiento por parte de los posibles intrusos, los administradores de sistemas deben abordar la seguridad de los datos y la información de manera proactiva.


NOTE: A partir de julio de 2024, el contenido del informe técnico _TR-4569: Guía de refuerzo de la seguridad para ONTAP_, publicado anteriormente como PDF, está disponible en docs.netapp.com.
