---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
permalink: business-continuity.html 
summary: Estos informes técnicos ofrecen una descripción general de la continuidad del negocio en NetApp ONTAP además de prácticas recomendadas 
---
= Informes técnicos sobre continuidad empresarial
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ofrece una amplia gama de soluciones que racionalizan dónde residen los datos y las aplicaciones para mejorar el rendimiento de forma rentable. Protección de datos, replicación y disponibilidad continua: La gestión de datos de ONTAP puede simplificar la protección de datos con una gestión de políticas que solo necesita configurar y olvidarse, a la vez que permite la continuidad del negocio con MetroCluster y SnapMirror Business Continuity.

[NOTE]
====
Estos informes técnicos se amplían en la link:https://docs.netapp.com/us-en/ontap/smbc/index.html["Continuidad del negocio con SnapMirror de ONTAP"] y.. link:https://docs.netapp.com/us-en/ontap-metrocluster/index.html["ONTAP MetroCluster"] documentación de productos.

====


== Continuidad del negocio de SnapMirror (SM-BC)

link:https://www.netapp.com/pdf.html?item=/media/21888-tr-4878.pdf["TR-4878: Continuidad del negocio con SnapMirror (SM-BC)"^]
SnapMirror Business Continuity (SM-BC) es una solución de almacenamiento de disponibilidad continua con granularidad a nivel de aplicación, disponible para ONTAP ejecutándose en sistemas de almacenamiento AFF o de cabinas All SAN (ASA), para satisfacer las necesidades de RPO 0 y RTO 0 de las aplicaciones empresariales más importantes.



== MetroCluster

link:https://www.netapp.com/pdf.html?item=/media/13480-tr4705.pdf["TR-4705: Arquitectura y diseño de la solución NetApp MetroCluster"^]
Este documento describe los conceptos de diseño y arquitectura de alto nivel para las funciones de MetroCluster en ONTAP.

*IP de MetroCluster*
link:http://www.netapp.com/us/media/tr-4689.pdf["TR-4689: Dirección IP de NetApp MetroCluster"^]
MetroCluster es una solución de almacenamiento de disponibilidad continua para ONTAP que se ejecuta en sistemas FAS y AFF. MetroCluster IP es un producto de última generación que utiliza un entramado de almacenamiento back-end basado en Ethernet. MetroCluster IP proporciona una configuración altamente redundante para satisfacer las necesidades de las aplicaciones empresariales más importantes. MetroCluster IP se incluye en ONTAP y proporciona conectividad NAS y SAN a los clientes y servidores que utilizan almacenamiento de ONTAP.

*MetroCluster FC*
link:https://www.netapp.com/pdf.html?item=/media/13482-tr4375.pdf["TR-4375: FC de NetApp MetroCluster"^]
MetroCluster proporciona una disponibilidad de datos continua en centros de datos separados geográficamente para aplicaciones críticas para la empresa. Obtenga más información sobre las prácticas recomendadas, las decisiones de diseño y las configuraciones compatibles con MetroCluster FC.
