---
permalink: networking.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, best practices, best-practices 
summary: Estos informes técnicos ofrecen una descripción general de las redes en NetApp ONTAP además de las prácticas recomendadas. 
---
= Informes técnicos de red de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP proporciona una variedad de diferentes capacidades y configuraciones de red para satisfacer las aplicaciones más exigentes de escalabilidad horizontal. Gracias a las funciones y capacidades de red, las empresas pueden crear un acceso fiable y seguro a sus datos.

[NOTE]
====
Estos informes técnicos se amplían en link:https://docs.netapp.com/us-en/ontap/network-management/index.html["Gestión de red de ONTAP"^]la documentación del producto.

====


[[routing]]
== Enrutamiento

link:https://www.netapp.com/pdf.html?item=/media/79703-TR-4949.pdf["Informe técnico TR-4949: BGP/VIP con ONTAP en el centro de datos"^]
Aprenda a implementar rápidamente una configuración BGP básica en ONTAP.



[[name-services]]
== Servicios de nombres

link:https://www.netapp.com/pdf.html?item=/media/19370-tr-4523.pdf["TR-4523: Balanceo de carga de DNS en ONTAP"^]
Aprenda a configurar ONTAP para su uso con metodologías de equilibrio de carga de DNS, incluido DNS en ONTAP, varios métodos de configuración y prácticas recomendadas.

link:https://www.netapp.com/pdf.html?item=/media/16328-tr-4668.pdf["TR-4668: Guía de prácticas recomendadas de servicios de nombres"^]
Conozca las prácticas recomendadas, los límites y las consideraciones que se deben tener en cuenta en la implementación de soluciones de almacenamiento conectado a la red (NAS), como CIFS/SMB y NFS en ONTAP.

link:https://www.netapp.com/pdf.html?item=/media/19423-tr-4835.pdf["TR-4835: Cómo configurar LDAP en la gestión de identidades NAS multiprotocolo de ONTAP"^]
Aprenda a configurar la gestión de identidades del protocolo ligero de acceso a directorios (LDAP) en ONTAP para NAS multiprotocolo.
