---
settings:
  name: ONTAP technical reports
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Informes técnicos de ONTAP
    url: "/index.html"
  - title: Aplicaciones y bases de datos
    url: "/apps-dbs.html"
  - title: Continuidad del negocio
    url: "/business-continuity.html"
  - title: Protección de datos y recuperación ante desastres
    url: "/data-protection-disaster-recovery.html"
  - title: FlexCache y FlexGroup Volumes
    url: "/nas-containers.html"
  - title: NAS
    url: "/nas.html"
  - title: Redes
    url: "/networking.html"
  - title: SAN
    url: "/san.html"
  - title: Seguridad
    url: "/security.html"
  - title: Guías de refuerzo de seguridad
    url: "/security-hardening-guides.html"
  - title: SnapCenter
    url: "/snapcenter.html"
  - title: Organización en niveles
    url: "/tiering.html"
  - title: Virtualización
    url: "/virtualization.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
