---
layout: landing-page 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, SAN, NVMe, NVMeoF, NVMeoTCP, NVMeoFC, iSCSI, fibre channel, fiber channel, igroups, namespaces, namespace, LUN, subsystem, best practices, best-practices 
permalink: san.html 
summary: Estos informes técnicos ofrecen una descripción general de los protocolos de bloque en ONTAP, así como prácticas recomendadas. 
---
= Informes técnicos de SAN
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
El almacenamiento SAN de ONTAP ofrece una experiencia SAN simplificada que proporciona alta disponibilidad para las bases de datos críticas para la misión de su organización y otras cargas de trabajo SAN. Gracias a la mejor integración de servicios de datos con bases de datos de Oracle, SAP y Microsoft SQL Server, además de VMware y otros hipervisores líderes, la solución SAN de ONTAP ofrece una rentabilidad de la inversión acelerada para las aplicaciones de bases de datos empresariales.

[NOTE]
====
Estos informes técnicos se amplían en la link:https://docs.netapp.com/us-en/ontap/san-management/index.html["Gestión de almacenamiento SAN de ONTAP"] documentación de productos.

====
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["TR-4080: Prácticas recomendadas para SAN modernas en ONTAP"^]
Obtenga información sobre los protocolos de bloque en ONTAP y las prácticas de recomendaciones.

link:https://www.netapp.com/pdf.html?item=/media/10681-tr4684.pdf["TR-4684: Implementación y configuración de SAN modernas con NVMe sobre entramados (NVMe-oF)"^]
Descubra cómo implementar y configurar los transportes NVMe over Fabrics (NVMe over Fibre Channel y NVMe over TCP). Los temas incluyen el diseño, la implementación, la configuración, directrices de gestión y prácticas recomendadas para crear soluciones SAN modernas de alto rendimiento y altamente disponibles que utilicen protocolos y transportes NVMe.

link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["TR-4968: Integridad y disponibilidad de datos de cabinas All-SAN de NetApp"^]
Descubra cómo funcionan las distintas funciones de protección e integridad de datos de un sistema de cabina All SAN para conseguir el máximo tiempo de actividad de las aplicaciones, además de las prácticas recomendadas para diseñar, implementar y gestionar una red SAN.

link:https://www.netapp.com/pdf.html?item=/media/9222-nva-1145-design.pdf["Solución flash SAN moderna conectada al cloud"^]
Esta arquitectura verificada de NetApp ha sido diseñada y verificada conjuntamente por NetApp, VMware yBroadcom. Utiliza las últimas soluciones de tecnología Brocade, Emulex y VMware vSphere junto con el almacenamiento all-flash de NetApp, que establece un nuevo estándar en el almacenamiento SAN empresarial y la protección de datos que ofrecerá un valor empresarial superior.
