---
permalink: security-hardening-guides.html 
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, MFA, best practices, best-practices, TR-4569 
summary: Estos informes técnicos proporcionan directrices sobre cómo reforzar NetApp ONTAP y otros productos relacionados con ONTAP. 
---
= Guías de refuerzo de seguridad de ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Estos informes técnicos ofrecen directrices sobre cómo fortalecer NetApp ONTAP y otros productos de NetApp.

[NOTE]
====
Estos informes técnicos se amplían en link:https://docs.netapp.com/us-en/ontap/security-encryption/index.html["Seguridad y cifrado de datos ONTAP"^]la documentación del producto.

====


== Guías de refuerzo

link:./ontap-security-hardening/security-hardening-overview.html["TR-4569: Guía de refuerzo de la seguridad para NetApp ONTAP"] Aprenda a configurar NetApp ONTAP para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos para la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-otv-hardening-overview.html["Guía de seguridad reforzada para herramientas de ONTAP para VMware vSphere"^] Aprenda a configurar las herramientas de ONTAP para VMware vSphere para ayudar a las empresas a cumplir los objetivos de seguridad prescritos de la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://www.netapp.com/pdf.html?item=/media/82393-tr-4957.pdf["TR-4957: Guía de refuerzo de la seguridad para NetApp SnapCenter"^]
Aprenda a configurar el software NetApp SnapCenter para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos sobre la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://www.netapp.com/pdf.html?item=/media/83591-tr-4963.pdf["TR-4963: Guía de refuerzo de la seguridad: Cloud Backup de BlueXP para aplicaciones"^]
Aprenda a configurar Cloud Backup de NetApp para aplicaciones para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos de la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://netapp.com/pdf.html?item=/media/78654-tr-4943.pdf["TR-4943: Guía de refuerzo de la seguridad para NetApp Active IQ Unified Manager"^]
Aprenda a configurar NetApp Active IQ Unified Manager para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos para la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://www.netapp.com/pdf.html?item=/media/78941-tr-4945.pdf["TR-4945: Guía de refuerzo de la seguridad para SDK de capacidad de gestión de NetApp"^]
Aprenda a configurar el SDK de capacidad de gestión de NetApp (NMSDK) para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos para la confidencialidad, la integridad y la disponibilidad de los sistemas de información.

link:https://docs.netapp.com/us-en/ontap-metrocluster/tiebreaker/install_security.html["Guía de refuerzo de seguridad para host y base de datos de MetroCluster tiebreaker"^] Aprenda a configurar el host y la base de datos de NetApp MetroCluster tiebreaker para ayudar a las organizaciones a cumplir los objetivos de seguridad prescritos para la confidencialidad, la integridad y la disponibilidad de los sistemas de información.
