---
sidebar: sidebar 
keywords: Technical Reports, TR, NetApp TR, ONTAP TR, ONTAP, ONTAP 9, VMware, vVols, SRM, SRA, Site Recovery Manager, OTV, ONTAP Tools for VMware, SnapCenter for VMware, SnapCenter, RCU, VSC, Virtual Storage Console, best practices, best-practices 
permalink: virtualization.html 
summary: Estos informes técnicos ofrecen una descripción general de las soluciones de virtualización de VMware utilizando NetApp ONTAP, así como prácticas recomendadas. 
---
= Informes técnicos de virtualización
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Las soluciones de virtualización de NetApp ayudan a sacar el máximo valor de sus servidores. Con una infraestructura de servidores virtuales con gran capacidad de respuesta basada en los pioneros sistemas flash ONTAP de alto rendimiento, podrá acceder a sus datos mucho más rápido. Su infraestructura virtual granular puede escalar sin provocar interrupciones del servicio hasta alcanzar varios petabytes de datos y ofrecer el rendimiento que necesita para garantizar el acceso compartido a varias cargas de trabajo. ONTAP ayuda a optimizar y reducir la complejidad de la puesta en marcha de su infraestructura de servidores virtuales con colaboraciones clave, indicaciones para la implementación, integración de aplicaciones y un diseño superior. ONTAP ofrece muchas prácticas y soluciones recomendadas para un entorno de virtualización sólido tanto en las instalaciones como en el cloud.

Estos informes técnicos se amplían en la link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["Herramientas de ONTAP para VMware vSphere"] documentación de productos.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vsphere-overview.html["TR-4597: VMware vSphere para ONTAP"]
 ONTAP ha sido una solución de almacenamiento líder para entornos de VMware vSphere durante casi dos décadas y continúa añadiendo funcionalidades innovadoras para simplificar la gestión al tiempo que reduce los costes. Este documento presenta la solución ONTAP para vSphere, incluyendo la información más reciente sobre el producto y las prácticas recomendadas para simplificar la puesta en marcha, reducir el riesgo y simplificar la gestión.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-vvols-overview.html["TR-4400: VMware vSphere Virtual Volumes (vVols) con ONTAP de NetApp"]
ONTAP ha sido una solución de almacenamiento líder para entornos VMware vSphere durante más de dos décadas y continúa añadiendo funcionalidades innovadoras para simplificar la gestión al tiempo que reduce los costes. Este documento trata las funcionalidades de ONTAP para VMware vSphere Virtual Volumes (vVols), incluida la información más reciente sobre el producto y los casos de uso, junto con las prácticas recomendadas y otra información para optimizar la puesta en marcha y reducir los errores.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-srm-overview.html["TR-4900: VMware Site Recovery Manager con NetApp ONTAP"]
ONTAP ha sido una solución de almacenamiento líder para entornos VMware vSphere desde su introducción en el centro de datos moderno en 2002, y continúa añadiendo funcionalidades innovadoras para simplificar la gestión y reducir los costes. Este documento presenta la solución ONTAP para VMware Site Recovery Manager (SRM), el software de recuperación ante desastres (DR) líder del sector de VMware, que incluye la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, reducir el riesgo y simplificar la gestión continua.

link:https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_auto_introduction.html["Introducción a la automatización para ONTAP y vSphere"]
La automatización ha sido un aspecto integral de la gestión de entornos VMware desde los primeros días de VMware ESX. La capacidad de poner en marcha infraestructura como código y ampliar las prácticas en operaciones de cloud privado ayuda a paliar las cuestiones relacionadas con el escalado, la flexibilidad, el aprovisionamiento automático y la eficiencia. Este documento presenta la solución de ONTAP para automatizar el entorno de ONTAP y VMware vSphere.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-security-tools.html["Artículo técnico WP-7353: Herramientas de ONTAP para VMware vSphere - Seguridad del producto"]
Este documento describe las técnicas y la tecnología empleadas para proteger las herramientas de ONTAP para VMware vSphere 9.X de las amenazas existentes y emergentes en entornos de productos.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware-security-snapcenter.html["WP-7355: Complemento SnapCenter Vmware vSphere - Seguridad del producto"]
Este documento describe las técnicas y la tecnología utilizadas para proteger el complemento NetApp SnapCenter para VMware vSphere 4.X de las amenazas existentes y emergentes en entornos de productos.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/microsoft/win_overview.html["TR-4568: Directrices de puesta en marcha de NetApp y prácticas recomendadas de almacenamiento para Windows Server"]
Microsoft Windows Server es un sistema operativo de clase empresarial que cubre redes, seguridad, virtualización, cloud, infraestructura de puestos de trabajo virtuales protección de acceso, protección de información, servicios web, infraestructura de plataformas de aplicaciones y mucho más. Este documento se centra en Microsoft Windows, donde se presta un especial énfasis en la tecnología de virtualización de Hyper-V, incluida la información de producto más reciente y las prácticas recomendadas para simplificar la puesta en marcha, reducir los riesgos y simplificar la gestión.
