---
permalink: zero-trust/zero-trust-cloud-deployments.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, cloud, deployments, hybrid, amazon web services, aws, microsoft azure, google cloud platform, gcp, GCNV, Google Cloud, Google Cloud NetApp Volumes 
summary: Las opciones de NetApp llevan los sistemas de gestión de datos en las instalaciones al cloud híbrido gracias a proveedores de cloud líderes que admiten controles de seguridad de confianza cero 
---
= Puesta en marcha de cloud híbrido y confianza cero
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp es la autoridad de datos para la nube híbrida. NetApp ofrece una variedad de opciones para ampliar los sistemas de gestión de datos locales a la nube híbrida con Amazon Web Services (AWS), Microsoft Azure, Google Cloud y otros proveedores de nube líderes. Las soluciones de nube híbrida de NetApp admiten los mismos controles de seguridad Zero Trust que están disponibles con los sistemas ONTAP locales y el almacenamiento definido por software ONTAP Select .

Puede ampliar fácilmente la capacidad en nubes públicas sin las restricciones típicas de CAPEX mediante el uso de servicios de archivos nativos de la nube de clase empresarial para AWS (FSxN), Google Cloud (GCNV) y Azure NetApp Files para Microsoft Azure. Ideales para cargas de trabajo intensivas en datos, como análisis y DevOps, estos servicios de datos en la nube combinan almacenamiento elástico bajo demanda como servicio de NetApp con gestión de datos ONTAP en una oferta completamente administrada.

ONTAP permite el movimiento de datos entre sus sistemas ONTAP locales y el entorno de almacenamiento de AWS, Google Cloud o Azure con el software de replicación de datos SnapMirror de NetApp .
