---
permalink: zero-trust/zero-trust-automation-orchestration.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, ontap, netapp, security, automation, orchestration, control, ansible 
summary: Gracias a la automatización, las organizaciones pueden escalar las puestas en marcha de Zero Trust más allá de procedimientos manuales para defenderse frente a actividades engañosas que también están automatizadas 
---
= Controles de orquestación y automatización de la seguridad de NetApp externos a ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La automatización le permite realizar un proceso o procedimiento con una asistencia humana mínima. Gracias a la automatización, las organizaciones pueden escalar sus puestas en marcha de confianza cero más allá de los procedimientos manuales para defenderse frente a actividades engañosas que también están automatizadas.

Ansible es una herramienta de aprovisionamiento de software de código abierto, gestión de configuración y puesta en marcha de aplicaciones. Se ejecuta en muchos sistemas similares a Unix, y puede configurar tanto sistemas similares a Unix como Microsoft Windows. Incluye su propio lenguaje declarativo para describir la configuración del sistema. Ansible fue escrito por Michael DeHaan y adquirido por Red Hat en 2015. Ansible no tiene agentes, se conecta temporalmente de forma remota a través de SSH o Administración remota de Windows (lo que permite la ejecución remota de PowerShell) para realizar tareas. NetApp ha desarrollado más que https://www.netapp.com/us/getting-started-with-netapp-approved-ansible-modules/index.aspx["150 Módulos Ansible para software ONTAP"^], lo que permite una mayor integración con el marco de automatización de Ansible. Los módulos de Ansible para NetApp proporcionan un conjunto de instrucciones para definir el estado deseado y transmitirlo al entorno NetApp de destino. Los módulos se incorporarán para dar soporte a tareas como configurar licencias, crear agregados y máquinas virtuales de almacenamiento, crear volúmenes y restaurar instantáneas, entre otras. Una función de Ansible ha sido https://github.com/NetApp/ansible/tree/master/nar_ontap_security_ucd_guide["Publicado en GitHub"^] específica de la guía de implementación de funcionalidades unificadas para departamentos de NetApp (UC).

Al utilizar los módulos disponibles de la biblioteca, los usuarios pueden desarrollar fácilmente playbooks de Ansible y personalizarlos para sus propias aplicaciones y necesidades empresariales para automatizar tareas mundanas. Después de escribir un playbook, puede ejecutarlo para ejecutar la tarea especificada, lo que ahorra tiempo y mejora la productividad. NetApp ha creado y compartido playbooks de muestra que puede utilizar directamente o personalizar según sus necesidades.

Data Infrastructure Insights es una herramienta de monitoreo de infraestructura que le brinda visibilidad de su infraestructura completa.  Con Data Infrastructure Insights, puede supervisar, solucionar problemas y optimizar todos sus recursos, incluidas sus instancias de nube pública y sus centros de datos privados.  Data Infrastructure Insights puede reducir el tiempo medio de resolución en un 90 % y evitar que el 80 % de los problemas de la nube afecten a los usuarios finales.  También puede reducir los costos de infraestructura en la nube en un promedio del 33% y reducir su exposición a amenazas internas al proteger sus datos con inteligencia procesable.  La capacidad de seguridad de la carga de trabajo de almacenamiento de Data Infrastructure Insights permite el análisis del comportamiento del usuario con IA y ML para alertar cuando se producen comportamientos aberrantes del usuario debido a una amenaza interna.  Para ONTAP, Storage Workload Security utiliza el motor Zero Trust FPolicy.
