---
sidebar: sidebar 
permalink: afx/afx-architecture.html 
keywords: netapp afx, architecture, storage availability zone, nvram, raid, disaggregated 
summary: NetApp AFX introduce diferencias arquitectónicas significativas respecto a ONTAP unificado en cómo se presenta el almacenamiento, cómo interactúan los nodos con los discos y cómo se gestiona la capacidad. 
---
= Cómo la arquitectura NetApp AFX difiere de ONTAP unificado
:allow-uri-read: 
:icons: font
:imagesdir: ../media/afx/


[role="lead"]
NetApp AFX introduce diferencias arquitectónicas significativas respecto a ONTAP unificado en cómo se presenta el almacenamiento, cómo interactúan los nodos con los discos y cómo se gestiona la capacidad.

Anteriormente, mostramos una imagen general de cómo la arquitectura unificada de ONTAP proporciona almacenamiento de archivos, objetos y bloques de datos a través de pares de HA conectados directamente que poseen sus propios conjuntos de discos y presentan capacidad física a través de agregados de discos. En esta sección, analizaremos con más detalle algunas de las principales diferencias entre las arquitecturas unificadas de ONTAP y NetApp AFX.



[[how-to-tell-if-a-system-is-running-netapp-afx]]
== Cómo saber si un sistema está ejecutando NetApp AFX

La principal forma de ver si tu sistema está ejecutando NetApp AFX es ejecutar el siguiente comando:

[listing]
----
AFX::> node show -fields personality
node             personality
---------------- -----------
afx-01           AFX
afx-02           AFX
----
Otra pista es la nueva Storage Availability Zone, pero ese también es un concepto disponible en NetApp All-SAN Arrays (ASA). Puedes ver tu capacidad a través de ese comando.

[listing]
----
AFX::> storage availability-zone show
                     Availability Zone Name: storage_availability_zone_0
                     Availability Zone UUID: 545cb59f-32e9-11f1-a2f5-d039eabdd925
                                 Total Size: 69.59TB
                              Physical Used: 837.1GB
                      Physical Used Percent: 1%
                                  Available: 68.77TB
                              Metadata Used: 837.1GB
                  Log and Recovery Metadata: 834.6GB
                              Delayed Frees: 2.50GB
 Physical User Data Without Snapshot Copies: 17.24MB
  Logical User Data Without Snapshot Copies: 17.24MB
   Efficiency Ratio Without Snapshot Copies: 1.00:1
               Space Full Threshold Percent: 98%
        Space Nearly Full Threshold Percent: 95%
----


[[architecture-topics]]
== Temas de arquitectura

* link:afx-architecture-node-disk.html["Relaciones entre nodos y discos"]
* link:afx-architecture-capacity-pool.html["Pool de capacidad única"]
* link:afx-architecture-nvram-ha.html["Comportamiento de la NVRAM replicada y de la conmutación por error en alta disponibilidad"]
* link:afx-architecture-independent-scale.html["Escala lineal independiente"]
* link:afx-architecture-raid.html["Cambios en RAID"]
* link:afx-architecture-storage-efficiency.html["Eficiencia del almacenamiento"]
* link:afx-architecture-feature-support.html["Cambios en la compatibilidad con las funciones de ONTAP"]
* link:afx-architecture-flexgroup.html["Mejoras en la gestión de FlexGroup"]
* link:afx-architecture-volume-moves.html["Movimientos de volúmenes"]
* link:afx-architecture-cluster-scale.html["Escala de clúster"]
* link:afx-architecture-root-volume.html["Cambios en el volumen raíz"]


[cols="1,1"]
|===


| link:afx-whats-new.html["Anterior"] | link:afx-architecture-node-disk.html["Siguiente: Relaciones entre nodos y discos"] 
|===